//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aguas_CirueloDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cirueloEntities : DbContext
    {
        public cirueloEntities()
            : base("name=cirueloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes_tb> Clientes_tb { get; set; }
        public virtual DbSet<Pagos_tb> Pagos_tb { get; set; }
        public virtual DbSet<Precios_tb> Precios_tb { get; set; }
        public virtual DbSet<Usuarios_tb> Usuarios_tb { get; set; }
    }
}
