//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aguas_CirueloDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes_tb()
        {
            this.Pagos_tb = new HashSet<Pagos_tb>();
        }
    
        public int Id_Cliente { get; set; }
        public string Clave_Cliente { get; set; }
        public string DNI_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Apellido_Cliente { get; set; }
        public string Direccion_Cliente { get; set; }
        public string Pilas_Cliente { get; set; }
        public string Tanques_Cliente { get; set; }
        public string Cisterna_Cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos_tb> Pagos_tb { get; set; }
    }
}
