//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aguas_CirueloDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_tb
    {
        public int Id_Usuarios { get; set; }
        public string DNI_Usuarios { get; set; }
        public string Nombre_Usuarios { get; set; }
        public string Apellido_Usuarios { get; set; }
        public string Contraseña_Usuarios { get; set; }
        public string Cargo_Usuarios { get; set; }
        public Nullable<int> Id_Pago { get; set; }
    
        public virtual Pagos_tb Pagos_tb { get; set; }
    }
}
